set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tmhedberg/SimpylFold'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-syntastic/syntastic'
"Plugin 'nvie/vim-flake8'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-unimpaired'
Plugin 'Chiel92/vim-autoformat'

call vundle#end()
filetype plugin indent on

" no more escape!
inoremap jk <Esc>
" Relative line number and ruler
set relativenumber
set ruler

" Enable folding
set foldmethod=indent
set foldlevel=99
" Enable folding with the spacebar
nnoremap <space> za

set hlsearch "highlight matches of the searched string
set tags=./.tags;/

set showcmd "show the typing command
set showmode "show the current mode
set visualbell "disable audio bell
syntax on

"map keys to add parentheses/curly braces around a word
map \p i(<Esc>ea)<Esc>
map \c i{<Esc>ea}<Esc>

vmap X y/<C-R>"<CR>
" Flag unwanted whitespace, following problematic
" au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match ExtraWhiteSpace /\s\+$/
let python_highlight_all=1

" Python Indentation
autocmd BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |
    \ set encoding=utf-8 |

" Full stack dev Indentation
au BufNewFile,BufRead *.js, *.html, *.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |

" ==========Plugin settings===========
" YouCompleteMe
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

" See the docstrings for the folded code
let g:SimpylFold_docstring_preview=1

"ignore files in NERDTree
let NERDTreeIgnore=['\.pyc$', '\~$']

" Syntastic
" automatically load errors into the location list
let g:syntastic_always_populate_loc_list = 1
" disable check for errors whenever you save the file
let g:syntastic_check_on_wq = 0
" check file syntax on open
let g:syntastic_check_on_open = 1
